const { expect } = require("chai");
const { ethers } = require("hardhat");
const crypto = require("crypto");
const { MerkleTree } = require("../../chain/merkle");

describe("DebrisLedger Smart Contract", function () {
  let debrisLedger, dataCredit;
  let owner, operator1, buyer, publisher;
  const accessFee = ethers.parseUnits("100", 18);

  beforeEach(async function () {
    [owner, operator1, buyer, publisher] = await ethers.getSigners();

    // Deploy DataCredit
    const DataCreditFactory = await ethers.getContractFactory("DataCredit");
    dataCredit = await DataCreditFactory.deploy();
    await dataCredit.waitForDeployment();

    // Deploy DebrisLedger
    const DebrisLedgerFactory = await ethers.getContractFactory("DebrisLedger");
    debrisLedger = await DebrisLedgerFactory.deploy(await dataCredit.getAddress(), accessFee);
    await debrisLedger.waitForDeployment();

    // Authorize operator1
    await debrisLedger.setOperator(operator1.address, true);

    // Fund buyer with ODC
    await dataCredit.transfer(buyer.address, ethers.parseUnits("1000", 18));
  });

  it("Allows authorized operator to anchor a block Merkle root", async function () {
    const root = "0x" + "ab12".repeat(16);
    const blockIndex = 1;
    const recordCount = 40;
    const blockTimestamp = 1782864000;

    const tx = await debrisLedger.connect(operator1).anchorRoot(blockIndex, root, recordCount, blockTimestamp);
    await expect(tx).to.emit(debrisLedger, "RootAnchored")
      .withArgs(blockIndex, root, recordCount, blockTimestamp, operator1.address);

    const anchor = await debrisLedger.anchors(blockIndex);
    expect(anchor.merkleRoot).to.equal(root);
    expect(anchor.recordCount).to.equal(recordCount);
    expect(anchor.anchoredBy).to.equal(operator1.address);
  });

  it("Rejects unauthorized account trying to anchor a root", async function () {
    const root = "0x" + "1122".repeat(16);
    await expect(
      debrisLedger.connect(buyer).anchorRoot(1, root, 40, 1782864000)
    ).to.be.revertedWithCustomError(debrisLedger, "UnauthorizedOperator");
  });

  it("Rejects duplicate anchoring for the same block index", async function () {
    const root = "0x" + "ab12".repeat(16);
    await debrisLedger.connect(operator1).anchorRoot(1, root, 40, 1782864000);

    await expect(
      debrisLedger.connect(operator1).anchorRoot(1, root, 40, 1782864000)
    ).to.be.revertedWithCustomError(debrisLedger, "BlockAlreadyAnchored");
  });

  it("Verifies on-chain SHA-256 Merkle proofs generated by JavaScript merkle.js", async function () {
    // Generate 40 record hashes in JavaScript
    const sha256 = (str) => crypto.createHash("sha256").update(str).digest("hex");
    const leaves = Array.from({ length: 40 }, (_, i) => sha256(`satellite_record_epoch_${i}`));

    // Build Merkle tree in JavaScript
    const tree = new MerkleTree(leaves);
    const root = tree.getRoot(true);

    // Anchor root on-chain
    const blockIndex = 5;
    await debrisLedger.anchorRoot(blockIndex, root, 40, 1782864000);

    // Test proof verification for leaf #14 and leaf #39
    const testIndices = [0, 14, 27, 39];
    for (const idx of testIndices) {
      const proofObj = tree.getProof(idx);

      // Call on-chain verifyRecord view function
      const isValid = await debrisLedger.verifyRecord(
        blockIndex,
        proofObj.leafHash,
        proofObj.proof,
        proofObj.leafIndex
      );

      expect(isValid).to.equal(true, `On-chain verification failed for leaf index ${idx}`);
    }
  });

  it("Rejects on-chain proof if leaf hash or sibling hash is corrupted", async function () {
    const sha256 = (str) => crypto.createHash("sha256").update(str).digest("hex");
    const leaves = Array.from({ length: 8 }, (_, i) => sha256(`record_${i}`));
    const tree = new MerkleTree(leaves);
    const root = tree.getRoot(true);

    const blockIndex = 8;
    await debrisLedger.anchorRoot(blockIndex, root, 8, 1782864000);

    const proofObj = tree.getProof(3);

    // Corrupt the leaf
    const wrongLeaf = "0x" + "ff".repeat(32);
    const resultWrongLeaf = await debrisLedger.verifyRecord(
      blockIndex,
      wrongLeaf,
      proofObj.proof,
      proofObj.leafIndex
    );
    expect(resultWrongLeaf).to.equal(false);

    // Corrupt a sibling in the proof
    const corruptedProof = [...proofObj.proof];
    corruptedProof[0] = "0x" + "00".repeat(32);
    const resultWrongSibling = await debrisLedger.verifyRecord(
      blockIndex,
      proofObj.leafHash,
      corruptedProof,
      proofObj.leafIndex
    );
    expect(resultWrongSibling).to.equal(false);
  });

  it("Executes dataset access purchase using DataCredit tokens via approve and transferFrom", async function () {
    const blockIndex = 12;
    const root = "0x" + "3344".repeat(16);
    await debrisLedger.anchorRoot(blockIndex, root, 40, 1782864000);

    // Buyer approves DebrisLedger to spend accessFee
    const debrisLedgerAddress = await debrisLedger.getAddress();
    await dataCredit.connect(buyer).approve(debrisLedgerAddress, accessFee);

    // Verify initial access is false
    expect(await debrisLedger.hasAccess(blockIndex, buyer.address)).to.equal(false);

    // Buyer calls buyAccess
    const tx = await debrisLedger.connect(buyer).buyAccess(blockIndex, publisher.address);
    await expect(tx).to.emit(debrisLedger, "AccessPurchased")
      .withArgs(blockIndex, buyer.address, publisher.address);

    // Verify tokens were transferred to publisher
    expect(await dataCredit.balanceOf(publisher.address)).to.equal(accessFee);

    // Verify buyer now has access
    expect(await debrisLedger.hasAccess(blockIndex, buyer.address)).to.equal(true);
  });
});
